### ISSUE TITLE
Repository error - Can't find NoClippy

### ISSUE THREAD

**Issue by Lauthrec88** [UnknownX7/NoClippy#63]
hello! I added your custom repository to the Dalamud extension, but when searching for Plugins it gives the error "Download Failed. (link)". What can I do to solve the problem?

**Comment by Hoodie921** [comment]
I'm also experiencing this issue. I know I'm posting the week of the 7.2 update but I had this issue before the update release too.

#### Process

- Open `Dalamud Settings`
- Select the `Experimental` tab
- Scroll down to `Custom Plugin Repositories` section
- Paste link in URL section
- Make sure `Enabled` is selected
- Select `Save` button

I then get the error appearing in the Dalamud Plugin window.

URL i'm using:
```
https://raw.githubusercontent.com/UnknownX7/NoClippy/master/NoClippy.json
```

Weirdly, if I use the URL in any web browser, I can view the JSON file data without issue:
Web browser result:
```json
{
  "Author": "UnknownX",
  "Name": "NoClippy",
  "Punchline": "Reduces the effects of lag on certain aspects of the game, and can show GCD clips",
  "Description": "Reduces the effects of lag on certain aspects of the game, such as weaving and statuses. Usable as an alternative, or in addition, to XivAlexander.",
  "IconUrl": "",
  "ImageUrls": [
    ""
  ],
  "RepoUrl": "https://github.com/UnknownX7/NoClippy",
  "CategoryTags": [
    "jobs",
    "utility"
  ],
  "InternalName": "NoClippy",
  "AssemblyVersion": "9.9.9.9",
  "Changelog": ""
}
```

**Comment by venomin30** [comment]
@Hoodie921 A couple of questions:

1. Is this the only custom repo you use?
2. Do you use a tunnel/vpn/ping-reducer?

There are times that your tunnel/VPN/etc will interfere with Dalamud trying to pull custom repo addresses. See if the problem exists without any such service running.

**Comment by Hoodie921** [comment]
> 1. Is this the only custom repo you use?  

I have 2 other custom repos. I'm not at home atm and can't remember what they are exactly, but at least one is related to Mare/Penumbra.

> 2. Do you use a tunnel/vpn/ping-reducer?  

I sometimes use a VPN but the service wasn't even running when I tried to install NoClippy.

**Comment by Alwayzchasing** [comment]
I am also having this issue. No Vpn etc apps, and this is the only custom repo I use.

**Comment by Hoodie921** [comment]
I managed to pull the error from Dalamud's debug logs using the following:

1. From within the game typed the following into the chat bar and hit enter:
```
/xldev
```
2.  `Dalamud` tab --> `Set Log Level` --> `Debug`
3.  `Dalamud` tab --> `Open Log Window`
    - I had to minimise the debug window before continuing because it took up so much space
4.  Dalamud Settings --> Experimental tab,  I deselected one of the other experimental plugins so Dalamud detected a change and tried to download NoClippy again once i hit `Save`.
    - If you have no other experimental plugin, you can just deselect NoClippy, Save, Re-Select NoClippy and hit Save again.
5. Opened the Log Window and had this error in the logs:

```
15:05:31.188 | ERR | [PLUGINR] PluginMaster failed: https://raw.githubusercontent.com/UnknownX7/NoClippy/master/NoClippy.json
	Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[Dalamud.Plugin.Internal.Types.Manifest.RemotePluginManifest]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
	To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
	Path 'Author', line 2, position 11.
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
	   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
	   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in /_/Dalamud/Plugin/Internal/Types/PluginRepository.cs:line 122
```

Based on the log, it's expecting a JSON Array but it receives a JSON Object. When I saw this I checked the 2 other experimental plugins i'm using and they're both Arrays with one-or-many nested Objects

Examples:
1. MakePlace: https://raw.githubusercontent.com/jawslouis/MakePlacePlugin/master/MakePlacePlugin.json
2. Penumbra: https://raw.githubusercontent.com/Ottermandias/SeaOfStars/main/repo.json
